import {forEach} from '../../utils/array';
import {formatCSS} from '../../utils/css-text/format-css';
import {loadAsDataURL} from '../../utils/network';
import {getMatches} from '../../utils/text';

const blobRegex = /url\(\"(blob\:.*?)\"\)/g;

async function replaceBlobs(text: string) {
    const promises: Array<Promise<string>> = [];
    getMatches(blobRegex, text, 1).forEach((url) => {
        const promise = loadAsDataURL(url);
        promises.push(promise);
    });
    const data = await Promise.all(promises);
    return text.replace(blobRegex, () => `url("${data.shift()}")`);
}

const banner = `/*
   ____             _                  _       _     _
  |  _ \ _   _ ___| | ____      ___ __(_) __ _| |__ | |_
  | | | | | | / __| |/ /\ \ /\ / / '__| |/ _\` | '_ \| __|
  | |_| | |_| \__ \   <  \ V  V /| |  | | (_| | | | | |_
  |____/ \__,_|___/_|\_\  \_/\_/ |_|  |_|\__, |_| |_|\__|
                                         |___/
  https://github.com/blamechris/duskwright

  Generated by the Duskwright extension. This is not part of the page: it lives in
  a user-side layer the page cannot observe or serialize. Disable the extension and
  the document is byte-identical to what it always was.
*/

/*! Duskwright generated CSS | MIT https://github.com/blamechris/duskwright/blob/main/LICENSE
 *  Derived from Dark Reader (c) Dark Reader Ltd., MIT https://github.com/darkreader/darkreader */
`;

export async function collectCSS(): Promise<string> {
    const css = [banner];

    function addStaticCSS(selector: string, comment: string) {
        const staticStyle = document.querySelector(selector);
        if (staticStyle && staticStyle.textContent) {
            css.push(`/* ${comment} */`);
            css.push(staticStyle.textContent);
            css.push('');
        }
    }

    addStaticCSS('.darkreader--fallback', 'Fallback Style');
    addStaticCSS('.darkreader--user-agent', 'User-Agent Style');
    addStaticCSS('.darkreader--text', 'Text Style');
    addStaticCSS('.darkreader--invert', 'Invert Style');
    addStaticCSS('.darkreader--variables', 'Variables Style');

    const modifiedCSS: string[] = [];
    (document.querySelectorAll('.darkreader--sync') as NodeListOf<HTMLStyleElement>).forEach((element) => {
        forEach(element.sheet!.cssRules, (rule) => {
            rule && rule.cssText && modifiedCSS.push(rule.cssText);
        });
    });

    if (modifiedCSS.length) {
        const formattedCSS = formatCSS(modifiedCSS.join('\n'));
        css.push('/* Modified CSS */');
        css.push(await replaceBlobs(formattedCSS));
        css.push('');
    }

    addStaticCSS('.darkreader--override', 'Override Style');

    return css.join('\n');
}
